export enum OutMsgs
{
    PLAYER_LOGIN_IND = 12,
    PLAYER_LOGOUT_IND = 13,
    PLAYER_ENTER_ROOM_IND = 14,
    PLAYER_LEAVE_ROOM_IND = 15,
    PLAYER_READY_IND = 16,
    PLAYER_PASS_IND = 17,
    PLAYER_DEAL_IND = 18,
    PLAYER_DEAL_TIMEOUT_IND = 19,
}