from enum import IntEnum

class InMsgs(IntEnum):
    CLIENT_LOGIN_IND = 13
    CLIENT_LOGOUT_IND = 14
    CLIENT_ENTER_ROOM_IND = 15
    CLIENT_LEAVE_ROOM_IND = 16
    CLIENT_READY_IND = 17
    CLIENT_PASS_IND = 18
    CLIENT_DEAL_IND = 19
    CLIENT_DEAL_TIMEOUT_IND = 20