# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_to_server_msgs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import client_ready_ind_pb2 as client__ready__ind__pb2
import client_not_ready_ind_pb2 as client__not__ready__ind__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='client_to_server_msgs.proto',
  package='msg',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1b\x63lient_to_server_msgs.proto\x12\x03msg\x1a\x16\x63lient_ready_ind.proto\x1a\x1a\x63lient_not_ready_ind.proto\"s\n\x11\x43lientToServerMsg\x12+\n\x0e\x63lientReadyInd\x18\x01 \x01(\x0b\x32\x13.msg.ClientReadyInd\x12\x31\n\x11\x63lientNotReadyInd\x18\x02 \x01(\x0b\x32\x16.msg.ClientNotReadyIndb\x06proto3')
  ,
  dependencies=[client__ready__ind__pb2.DESCRIPTOR,client__not__ready__ind__pb2.DESCRIPTOR,])




_CLIENTTOSERVERMSG = _descriptor.Descriptor(
  name='ClientToServerMsg',
  full_name='msg.ClientToServerMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientReadyInd', full_name='msg.ClientToServerMsg.clientReadyInd', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clientNotReadyInd', full_name='msg.ClientToServerMsg.clientNotReadyInd', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=203,
)

_CLIENTTOSERVERMSG.fields_by_name['clientReadyInd'].message_type = client__ready__ind__pb2._CLIENTREADYIND
_CLIENTTOSERVERMSG.fields_by_name['clientNotReadyInd'].message_type = client__not__ready__ind__pb2._CLIENTNOTREADYIND
DESCRIPTOR.message_types_by_name['ClientToServerMsg'] = _CLIENTTOSERVERMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientToServerMsg = _reflection.GeneratedProtocolMessageType('ClientToServerMsg', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTTOSERVERMSG,
  '__module__' : 'client_to_server_msgs_pb2'
  # @@protoc_insertion_point(class_scope:msg.ClientToServerMsg)
  })
_sym_db.RegisterMessage(ClientToServerMsg)


# @@protoc_insertion_point(module_scope)
