# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_ready_ind.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client_ready_ind.proto',
  package='msg',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x63lient_ready_ind.proto\x12\x03msg\"\"\n\x0e\x43lientReadyInd\x12\x10\n\x08playerId\x18\x01 \x01(\x05\x62\x06proto3')
)




_CLIENTREADYIND = _descriptor.Descriptor(
  name='ClientReadyInd',
  full_name='msg.ClientReadyInd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerId', full_name='msg.ClientReadyInd.playerId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['ClientReadyInd'] = _CLIENTREADYIND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientReadyInd = _reflection.GeneratedProtocolMessageType('ClientReadyInd', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTREADYIND,
  '__module__' : 'client_ready_ind_pb2'
  # @@protoc_insertion_point(class_scope:msg.ClientReadyInd)
  })
_sym_db.RegisterMessage(ClientReadyInd)


# @@protoc_insertion_point(module_scope)
