# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_not_ready_ind.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client_not_ready_ind.proto',
  package='msg',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1a\x63lient_not_ready_ind.proto\x12\x03msg\"%\n\x11\x43lientNotReadyInd\x12\x10\n\x08playerId\x18\x01 \x01(\x05\x62\x06proto3')
)




_CLIENTNOTREADYIND = _descriptor.Descriptor(
  name='ClientNotReadyInd',
  full_name='msg.ClientNotReadyInd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerId', full_name='msg.ClientNotReadyInd.playerId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['ClientNotReadyInd'] = _CLIENTNOTREADYIND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientNotReadyInd = _reflection.GeneratedProtocolMessageType('ClientNotReadyInd', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTNOTREADYIND,
  '__module__' : 'client_not_ready_ind_pb2'
  # @@protoc_insertion_point(class_scope:msg.ClientNotReadyInd)
  })
_sym_db.RegisterMessage(ClientNotReadyInd)


# @@protoc_insertion_point(module_scope)
